# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: appName
    value: 'duuksawhmoodle01'
  - name: webAppResourceGroupName
    value: 'du-uks-awh-arc-moodle01'
  - name: runtimeStack
    value: 'PHP|8.1'
  - name: azureSubscription
    value: 'svc-con-awh-01'

steps:
  - script: |
      echo Downloading Moodle to "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      curl -o "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip" \
        https://download.moodle.org/download.php/stable401/moodle-4.1.2.zip
      cd $(Build.ArtifactStagingDirectory)
      mkdir ../s/release/
      cp $(Build.BuildId).zip ../s/release/
    displayName: Get Moodle Release and place in artefact staging directory

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      WebAppName: '$(appName)'
      ResourceGroupName: '$(webAppResourceGroupName)'
      azureSubscription: '$(azureSubscription)'
      deployToSlotOrASE: true
      SlotName: 'production'
      RuntimeStack: '$(runtimeStack)'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
      #StartupCommand: ''
      ScriptType: 'Inline Script'
      InlineScript: |
        echo "Working directory is $(pwd)"
        export WORKDIR=$(pwd)
        echo "php is $(which php)"
        echo "\$PYTHONPATH is $PYTHONPATH"
        echo "\$PATH is $PATH"

