# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: appName
    value: 'duuksawhmoodle01'
  - name: webAppResourceGroupName
    value: 'du-uks-awh-arc-moodle01'
  - name: runtimeStack
    value: 'PHP|8.1'
  - name: azureSubscription
    value: 'svc-con-awh-01'

steps:
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      WebAppName: '$(appName)'
      ResourceGroupName: '$(webAppResourceGroupName)'
      azureSubscription: '$(azureSubscription)'
      deployToSlotOrASE: true
      SlotName: 'production'
      RuntimeStack: '$(runtimeStack)'
      #StartupCommand: ''
      ScriptType: 'Inline Script'
      InlineScript: |
        echo "Working directory is $(pwd)"
        export WORKDIR=$(pwd)
        echo "php is $(which php)"
        echo "\$PYTHONPATH is $PYTHONPATH"
        echo "\$PATH is $PATH"

