# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr: none

pool:
  name: Default
  demands:
    - Agent.Name -equals vmlsha1

resources:
  - repo: self

variables:
  - group: arc-moodle01

  - name: appName
    value: 'duuksawhmoodle01'
  - name: webAppResourceGroupName
    value: 'du-uks-awh-arc-moodle01'
  - name: runtimeStack
    value: 'PHP|7.4'
  - name: azureSubscription
    value: 'svc-con-awh-01'
  - name: zipDistribution
    value: 'https://download.moodle.org/download.php/direct/stable401/moodle-4.1.2.zip'

jobs:
- job: Deployment
  steps:
# See https://docs.moodle.org/401/en/Installing_Moodle#Download_and_copy_files_into_place
# Alternate git download: `git clone -b MOODLE_{{Version3}}_STABLE git://git.moodle.org/moodle.
  - script: |
      set -e
      ls -lA
      
      mkdir -p dist
      cd dist
      
      echo Downloading Moodle from "$(zipDistribution)"
      curl --connect-timeout 20 --max-time 60 -L -o dist.zip "$(zipDistribution)"
      
      echo "Extracting folder..."
      unzip -q dist.zip
      rm dist.zip
      
      DIR=$(ls)
      (cd $(ls); mv * .* ../)
      rmdir $DIR
      
      cp ../*.php .
      mv config-dist.php config.php
      
      ESC_DATA_ROOT=$(printf '%s\n' "${DATA_ROOT}" | sed -e 's/[\/&]/\\&/g')      
      ESC_WWW_ROOT=$(printf '%s\n' "${WWW_ROOT}" | sed -e 's/[\/&]/\\&/g')
      
      sed -i '/$CFG->reverseproxy/s/^\/\/[ ]*//g' config.php
      sed -i -E "/$CFG->dbhost\s*= '[a-z]+';/s/localhost/${DB_HOST}/" config.php
      sed -i -E "/$CFG->dbname\s*= '[a-z]+';/s/moodle/${DB_NAME}/" config.php
      sed -i -E "/$CFG->dbuser\s*= '[a-z]+';/s/username/${DB_USER}/" config.php
      sed -i -E "/$CFG->dbpass\s*= '[a-z]+';/s/password/${DB_PASS}/" config.php
      sed -i -E "/$CFG->dataroot\s*= '.+';/s/\/home\/example\/moodledata/${ESC_DATA_ROOT}/" config.php
      sed -i -E "/$CFG->wwwroot\s*= '.+';/s/http:\/\/example.com\/moodle/${ESC_WWW_ROOT}/" config.php
    
      cat config.php | grep '^\$CFG\->reverseproxy'
      cat config.php | grep '^\$CFG\->dbhost'
      cat config.php | grep '^\$CFG\->dbname'
      cat config.php | grep '^\$CFG\->dbuser'
      cat config.php | grep '^\$CFG\->dbpass' | sed "s/${DB_PASS}/*******/"
      cat config.php | grep '^\$CFG\->dataroot'
      cat config.php | grep '^\$CFG\->wwwroot'

    displayName: Place Moodle in staging directory
    env:
      DB_HOST: $(DB_HOST)
      DB_NAME: $(DB_NAME)
      DB_USER: $(DB_USER)
      DB_PASS: $(DB_PASS)
      DATA_ROOT: $(DATA_ROOT)
      WWW_ROOT: $(WWW_ROOT)

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      appType: 'webAppLinux'
      deployToSlotOrASE: true
      SlotName: 'production'
      WebAppName: '$(appName)'
      ResourceGroupName: '$(webAppResourceGroupName)'
      azureSubscription: '$(azureSubscription)'
      RuntimeStack: '$(runtimeStack)'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      AppSettings: '-DATA_ROOT $(DATA_ROOT)'
      ScriptType: 'Inline Script'
      InlineScript: |
        set -e
        export WORKDIR=$(pwd)
        echo "Working directory is ${WORKDIR}"
        echo "I am $(whoami)"
             
        ls -lA | head
        echo "$(ls -lA | wc -l) files total"
        ls -lA ${DATA_ROOT}
        touch ${DATA_ROOT}/test
